name: CI

on:
  push:
    branches: [ nigthlybuild ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  SLN: ${{ github.workspace }}/src/git-istage.sln
  BIN: ${{ github.workspace }}/bin/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # We need the full history in order to use Git versioning
    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/*}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SLN
    - name: Build
      run: dotnet build --no-restore --nologo $SLN /p:OutDir=$BIN
    - name: Test
      run: dotnet test --no-build --nologo --verbosity normal $SLN /p:OutDir=$BIN
    - name: Push package to GPR
      if: ${{ github.event_name == 'push' && env.RELEASE_VERSION == 'nigthlybuild' }}
      run: dotnet nuget push $BIN*.nupkg --source https://nuget.pkg.github.com/jmelosegui/index.json --api-key ${{ github.token }} --skip-duplicate
